# encoding: utf8

# Import local files:
import colors as COLORS
import margins as MARGINS
import roi as ROI


# External:
external = ROI.ROI('External', 'External', COLORS.external)
x_external = ROI.ROI('xExternal', 'Organ', COLORS.external)
body = ROI.ROI('Body', 'Control', COLORS.body)

# Support:
couch = ROI.ROI('Couch', 'Undefined', COLORS.couch)
x_couch_full = ROI.ROI('xCouchFull', 'Undefined', COLORS.wall)

# Target volumes:
# GTV
gtv = ROI.ROI('GTV', 'Gtv', COLORS.gtv)
gtv1 = ROI.ROI('GTV1', 'Gtv', COLORS.gtv)
gtv2 = ROI.ROI('GTV2', 'Gtv', COLORS.gtv)
gtv3 = ROI.ROI('GTV3', 'Gtv', COLORS.gtv)
gtv4 = ROI.ROI('GTV4', 'Gtv', COLORS.gtv)
gtv_p = ROI.ROI('GTVp','Gtv', COLORS.gtv)
gtv_n = ROI.ROI('GTVn','Gtv', COLORS.gtv)
gtv_n1 = ROI.ROI('GTVn1','Gtv', COLORS.gtv)
gtv_n2 = ROI.ROI('GTVn2','Gtv', COLORS.gtv)
gtv_n3 = ROI.ROI('GTVn3','Gtv', COLORS.gtv)
gtv_n4 = ROI.ROI('GTVn4','Gtv', COLORS.gtv)
gtv_n5 = ROI.ROI('GTVn5','Gtv', COLORS.gtv)
gtv_n6 = ROI.ROI('GTVn6','Gtv', COLORS.gtv)
gtv_sb = ROI.ROI('GTVsb', 'Gtv', COLORS.gtv)
# IGTV
igtv = ROI.ROI('IGTV', 'Gtv', COLORS.gtv)
igtv1 = ROI.ROI('IGTV1', 'Gtv', COLORS.gtv)
igtv2 = ROI.ROI('IGTV2', 'Gtv', COLORS.gtv)
igtv3 = ROI.ROI('IGTV3', 'Gtv', COLORS.gtv)
igtv_p = ROI.ROI('IGTVp','Gtv', COLORS.gtv)
igtv_n = ROI.ROI('IGTVn','Gtv', COLORS.gtv)
igtv_n1 = ROI.ROI('IGTVn1','Gtv', COLORS.gtv_high)
igtv_n2 = ROI.ROI('IGTVn2','Gtv', COLORS.gtv_high)
igtv_n3 = ROI.ROI('IGTVn3','Gtv', COLORS.gtv_high)
igtv_n4 = ROI.ROI('IGTVn4','Gtv', COLORS.gtv_high)
igtv_n5 = ROI.ROI('IGTVn5','Gtv', COLORS.gtv_high)
igtv_n6 = ROI.ROI('IGTVn6','Gtv', COLORS.gtv_high)
# pt
gtv_p_pt = ROI.ROI('GTVp_PT', 'Gtv', COLORS.gtv_pt)
gtv_n_pt = ROI.ROI('GTVn_PT', 'Gtv', COLORS.gtv_pt)
gtv_n1_pt = ROI.ROI('GTVn1_PT', 'Gtv', COLORS.gtv_pt)
gtv_n2_pt = ROI.ROI('GTVn2_PT', 'Gtv', COLORS.gtv_pt)
gtv_n3_pt = ROI.ROI('GTVn3_PT', 'Gtv', COLORS.gtv_pt)
gtv_n4_pt = ROI.ROI('GTVn4_PT', 'Gtv', COLORS.gtv_pt)
gtv_n5_pt = ROI.ROI('GTVn5_PT', 'Gtv', COLORS.gtv_pt)
gtv_n6_pt = ROI.ROI('GTVn6_PT', 'Gtv', COLORS.gtv_pt)
gtv_pt = ROI.ROI('GTV_PT', 'Gtv', COLORS.gtv_pt)
# 66
gtv_p_66 = ROI.ROI('GTVp_66','Gtv', COLORS.gtv)
gtv_n_66 = ROI.ROI('GTVn_66','Gtv', COLORS.gtv)
# 64
gtv_n_64 = ROI.ROI('GTVn_64.4','Gtv', COLORS.gtv_high)
gtv_n1_64 = ROI.ROI('GTVn1_64.4','Gtv', COLORS.gtv_high)
gtv_n2_64 = ROI.ROI('GTVn2_64.4','Gtv', COLORS.gtv_high)
gtv_n3_64 = ROI.ROI('GTVn3_64.4','Gtv', COLORS.gtv_high)
gtv_n4_64 = ROI.ROI('GTVn4_64.4','Gtv', COLORS.gtv_high)
gtv_n5_64 = ROI.ROI('GTVn5_64.4','Gtv', COLORS.gtv_high)
# 60
gtv_p_60 = ROI.ROI('GTVp_60','Gtv', COLORS.gtv)
gtv_n_60 = ROI.ROI('GTVn_60','Gtv', COLORS.gtv)
# 59
gtv_n_59 = ROI.ROI('GTVn_58.8','Gtv', COLORS.gtv)
gtv_n1_59 = ROI.ROI('GTVn1_58.8','Gtv', COLORS.gtv)
gtv_n2_59 = ROI.ROI('GTVn2_58.8','Gtv', COLORS.gtv)
gtv_n3_59 = ROI.ROI('GTVn3_58.8','Gtv', COLORS.gtv)
gtv_n4_59 = ROI.ROI('GTVn4_58.8','Gtv', COLORS.gtv)
gtv_n5_59 = ROI.ROI('GTVn5_58.8','Gtv', COLORS.gtv)
# 57
gtv_p_57 = ROI.ROI('GTVp_57.5','Gtv', COLORS.gtv_high)
gtv_n_57 = ROI.ROI('GTVn_57.5','Gtv', COLORS.gtv_high)
gtv_n1_57 = ROI.ROI('GTVn1_57.5','Gtv', COLORS.gtv_high)
gtv_n2_57 = ROI.ROI('GTVn2_57.5','Gtv', COLORS.gtv_high)
gtv_n3_57 = ROI.ROI('GTVn3_57.5','Gtv', COLORS.gtv_high)
gtv_n4_57 = ROI.ROI('GTVn4_57.5','Gtv', COLORS.gtv_high)
gtv_n5_57 = ROI.ROI('GTVn5_57.5','Gtv', COLORS.gtv_high)
# 55
gtv_n_55 = ROI.ROI('GTVn_55','Gtv', COLORS.gtv)
gtv_n1_55 = ROI.ROI('GTVn1_55','Gtv', COLORS.gtv)
gtv_n2_55 = ROI.ROI('GTVn2_55','Gtv', COLORS.gtv)
gtv_n3_55 = ROI.ROI('GTVn3_55','Gtv', COLORS.gtv)
gtv_n4_55 = ROI.ROI('GTVn4_55','Gtv', COLORS.gtv)
gtv_n5_55 = ROI.ROI('GTVn5_55','Gtv', COLORS.gtv)
# 54
gtv_p_54 = ROI.ROI('GTVn_54','Gtv', COLORS.gtv)
gtv_n_54 = ROI.ROI('GTVn_54','Gtv', COLORS.gtv)
gtv_n1_54 = ROI.ROI('GTVn1_54','Gtv', COLORS.gtv)
gtv_n2_54 = ROI.ROI('GTVn2_54','Gtv', COLORS.gtv)
gtv_n3_54 = ROI.ROI('GTVn3_54','Gtv', COLORS.gtv)
gtv_n4_54 = ROI.ROI('GTVn4_54','Gtv', COLORS.gtv)
# 50
gtv_p_50 = ROI.ROI('GTVp_50','Gtv', COLORS.gtv)
gtv_n_50 = ROI.ROI('GTVn_50','Gtv', COLORS.gtv)
gtv_n1_50 = ROI.ROI('GTVn1_50','Gtv', COLORS.gtv)
gtv_n2_50 = ROI.ROI('GTVn2_50','Gtv', COLORS.gtv)
gtv_n3_50 = ROI.ROI('GTVn3_50','Gtv', COLORS.gtv)
gtv_n4_50 = ROI.ROI('GTVn4_50','Gtv', COLORS.gtv)
# 41.4
gtv_p_41_4 = ROI.ROI('GTVp_41.4','Gtv', COLORS.gtv)
gtv_n_41_4 = ROI.ROI('GTVn_41.4','Gtv', COLORS.gtv)

# CTV
ctv_underived = ROI.ROI('CTV', 'Ctv', COLORS.ctv)
ctv = ROI.ROIExpanded('CTV', 'Ctv', COLORS.ctv, gtv, margins = MARGINS.uniform_5mm_expansion)
ctv_l = ROI.ROI('CTV_L', 'Ctv', COLORS.ctv)
ctv_r = ROI.ROI('CTV_R', 'Ctv', COLORS.ctv)
ctv_p = ROI.ROI('CTVp', 'Ctv', COLORS.ctv)
ctv_n = ROI.ROI('CTVn','Ctv', COLORS.ctv_n)
ctv_e = ROI.ROI('CTVe','Ctv', COLORS.ctv_med)
ctv_p_l = ROI.ROI('CTVp_L', 'Ctv', COLORS.ctv)
ctv_n_l = ROI.ROI('CTVn_L','Ctv', COLORS.ctv_n)
ctv_p_r = ROI.ROI('CTVp_R', 'Ctv', COLORS.ctv)
ctv_n_r = ROI.ROI('CTVn_R','Ctv', COLORS.ctv_n)
ctv1 = ROI.ROI('CTV1', 'Ctv', COLORS.ctv)
ctv2 = ROI.ROI('CTV2', 'Ctv', COLORS.ctv)
ctv3 = ROI.ROI('CTV3', 'Ctv', COLORS.ctv)
ctv4 = ROI.ROI('CTV4', 'Ctv', COLORS.ctv)
ctv_sb = ROI.ROI('CTVsb', 'Ctv', COLORS.ctv)
ctv_n1 = ROI.ROI('CTVn1', 'Ctv', COLORS.ctv_high_2)
ctv_n2 = ROI.ROI('CTVn2', 'Ctv', COLORS.ctv_high_2)
ctv_n3 = ROI.ROI('CTVn3', 'Ctv', COLORS.ctv_high_2)
ctv_n4 = ROI.ROI('CTVn4', 'Ctv', COLORS.ctv_high_2)
ctv_n5 = ROI.ROI('CTVn5', 'Ctv', COLORS.ctv_high_2)
ctv_e_l = ROI.ROI('CTVe_L', 'Ctv', COLORS.ctv_low_2)
ctv_e_r = ROI.ROI('CTVe_R', 'Ctv', COLORS.ctv_low_2)
# ICTV
ictv = ROI.ROIExpanded('ICTV', 'Ctv', COLORS.ctv, igtv, margins = MARGINS.uniform_5mm_expansion)
ictv1 = ROI.ROIExpanded('ICTV1', 'Ctv', COLORS.ctv, igtv1, margins = MARGINS.uniform_5mm_expansion)
ictv2 = ROI.ROIExpanded('ICTV2', 'Ctv', COLORS.ctv, igtv2, margins = MARGINS.uniform_5mm_expansion)
ictv3 = ROI.ROIExpanded('ICTV3', 'Ctv', COLORS.ctv, igtv3, margins = MARGINS.uniform_5mm_expansion)
ictv_p = ROI.ROI('ICTVp', 'Ctv', COLORS.ctv_high)
ictv_n = ROI.ROI('ICTVn', 'Ctv', COLORS.ctv_n)
ictv_n1 = ROI.ROI('ICTVn1', 'Ctv', COLORS.ctv_high)
ictv_n2 = ROI.ROI('ICTVn2', 'Ctv', COLORS.ctv_high)
ictv_n3 = ROI.ROI('ICTVn3', 'Ctv', COLORS.ctv_high)
ictv_n4 = ROI.ROI('ICTVn4', 'Ctv', COLORS.ctv_high)
ictv_n5 = ROI.ROI('ICTVn5', 'Ctv', COLORS.ctv_high)
ictv_n6 = ROI.ROI('ICTVn6', 'Ctv', COLORS.ctv_high)
# 56
ctv_boost = ROI.ROI('CTVp_56', 'Ctv', COLORS.ctv_low_2)
ctv_boost_r = ROI.ROI('CTVp_56_R', 'Ctv', COLORS.ctv_low_2)
ctv_boost_l = ROI.ROI('CTVp_56_L', 'Ctv', COLORS.ctv_low_2)
# 54
ctv_e_l_54 = ROI.ROI('CTVe_L_54', 'Ctv', COLORS.ctv_low_2)
ctv_e_r_54 = ROI.ROI('CTVe_R_54', 'Ctv', COLORS.ctv_low_2)
# 50
ctv_e_l_50 = ROI.ROI('CTVe_L_50', 'Ctv', COLORS.ctv_low_2)
ctv_e_r_50 = ROI.ROI('CTVe_R_50', 'Ctv', COLORS.ctv_low_2)
# CTV for breast (should have changed their names)

ctv_n_imn = ROI.ROI('CTVn_IMN', 'Ctv', COLORS.imn)
imn = ROI.ROI('CTVn_IMN', 'Ctv', COLORS.imn)
#ctv_imn_l = ROI.ROI('CTVn_IMN_L', 'Ctv', COLORS.imn)
#ctv_imn_r = ROI.ROI('CTVn_IMN_R', 'Ctv', COLORS.imn)
ctv_n_imn_l_empty = ROI.ROI('CTVn_IMN_L', 'Ctv', COLORS.imn)
ctv_n_imn_r_empty = ROI.ROI('CTVn_IMN_R', 'Ctv', COLORS.imn)
level4 = ROI.ROI('CTVn_L4', 'Ctv', COLORS.level4)
level3 = ROI.ROI('CTVn_L3', 'Ctv', COLORS.level3)
level2= ROI.ROI('CTVn_L2', 'Ctv', COLORS.level2)
level1= ROI.ROI('CTVn_L1', 'Ctv', COLORS.level1)
level_interpect= ROI.ROI('CTVn_Interpect', 'Ctv', COLORS.level)
level4_l_empty = ROI.ROI('CTVn_L4_L', 'Ctv', COLORS.level4)
level3_l_empty = ROI.ROI('CTVn_L3_L', 'Ctv', COLORS.level3)
level2_l_empty = ROI.ROI('CTVn_L2_L', 'Ctv', COLORS.level2)
level1_l_empty = ROI.ROI('CTVn_L1_L', 'Ctv', COLORS.level1)
level_interpect_l_empty = ROI.ROI('CTVn_Interpect_L', 'Ctv', COLORS.level)
level4_r_empty = ROI.ROI('CTVn_L4_R', 'Ctv', COLORS.level4)
level3_r_empty = ROI.ROI('CTVn_L3_R', 'Ctv', COLORS.level3)
level2_r_empty = ROI.ROI('CTVn_L2_R', 'Ctv', COLORS.level2)
level1_r_empty = ROI.ROI('CTVn_L1_R', 'Ctv', COLORS.level1)
level_interpect_r_empty = ROI.ROI('CTVn_Interpect_R', 'Ctv', COLORS.level)

# Substitute ROI objects (only used for naming):
# Targets:
ptv = ROI.ROIExpanded('PTV', 'Ptv', COLORS.ptv, ctv, margins = MARGINS.uniform_5mm_expansion)
ptv_n1 = ROI.ROI('PTVn1', 'Ptv', COLORS.ptv)
ptv_n2 = ROI.ROI('PTVn2', 'Ptv', COLORS.ptv)
ptv_n3 = ROI.ROI('PTVn3', 'Ptv', COLORS.ptv)
ptv_n4 = ROI.ROI('PTVn4', 'Ptv', COLORS.ptv)
ptv_n5 = ROI.ROI('PTVn5', 'Ptv', COLORS.ptv)
ptv_n6 = ROI.ROI('PTVn6', 'Ptv', COLORS.ptv)
ptv1 =  ROI.ROI('PTV1', 'Ptv', COLORS.ptv)
ptv2 =  ROI.ROI('PTV2', 'Ptv', COLORS.ptv)
ptv3 =  ROI.ROI('PTV3', 'Ptv', COLORS.ptv)
ptv4 =  ROI.ROI('PTV4', 'Ptv', COLORS.ptv)
ptv_p = ROI.ROI('PTVp', 'Ptv', COLORS.x_ptv_54)
ptv_n =  ROI.ROI('PTVn', 'Ptv', COLORS.ptv)
ptv_c = ROI.ROI('PTVc', 'Ptv', COLORS.ptv)
ptv_sb = ROI.ROI('PTVsb', 'Ptv', COLORS.ptv)

# Head and neck
# 70
ctv_p_70 = ROI.ROI('CTVp_70', 'Ctv', COLORS.ctv_high_2)
ctv_n_70 = ROI.ROI('CTVn_70', 'Ctv', COLORS.ctv_high_2)
ctv_n1_70 = ROI.ROI('CTVn1_70', 'Ctv', COLORS.ctv_high_2)
ctv_n2_70 = ROI.ROI('CTVn2_70', 'Ctv', COLORS.ctv_high_2)
ctv_n3_70 = ROI.ROI('CTVn3_70', 'Ctv', COLORS.ctv_high_2)
ctv_n4_70 = ROI.ROI('CTVn4_70', 'Ctv', COLORS.ctv_high_2)
ptv_p_70 = ROI.ROI('PTVp_70', 'Ptv', COLORS.ptv_high_2)
# 68
ctv_p_68 = ROI.ROI('CTVp_68', 'Ctv', COLORS.ctv_high_2)
ctv_n_68 = ROI.ROI('CTVn_68', 'Ctv', COLORS.ctv_high_2)
ctv_n1_68 = ROI.ROI('CTVn1_68', 'Ctv', COLORS.ctv_high_2)
ctv_n2_68 = ROI.ROI('CTVn2_68', 'Ctv', COLORS.ctv_high_2)
ctv_n3_68 = ROI.ROI('CTVn3_68', 'Ctv', COLORS.ctv_high_2)
ctv_n4_68 = ROI.ROI('CTVn4_68', 'Ctv', COLORS.ctv_high_2)
ptv_n_68 = ROI.ROI('PTVn_68', 'Ptv', COLORS.ptv_high_2)
ptv_p_68 = ROI.ROI('PTVp_68', 'Ptv', COLORS.ptv_high_2)
# 66
ctv_p_66 = ROI.ROI('CTVp_66', 'Ctv', COLORS.ctv_high_2)
ctv_sb_66 = ROI.ROI('CTVsb_66', 'Ctv', COLORS.ctv_high_2)
ptv_sb_66 = ROI.ROI('PTVsb_66', 'Ptv', COLORS.ptv_high_2)
ptv_p_66 = ROI.ROI('PTVp_66', 'Ptv', COLORS.ptv_high_2)
# 64
ctv_sb_64 = ROI.ROI('CTVsb_64', 'Ctv', COLORS.ctv_high_2)
ptv_sb_64 = ROI.ROI('PTVsb_64', 'Ptv', COLORS.ptv_high_2)
# 60
ctv_p_60 = ROI.ROI('CTVp_60', 'Ctv', COLORS.ctv_med)
ctv_n_60 = ROI.ROI('CTVn_60', 'Ctv', COLORS.ctv_med)
ctv_n1_60 = ROI.ROI('CTVn1_60', 'Ctv', COLORS.ctv_med)
ctv_n2_60 = ROI.ROI('CTVn2_60', 'Ctv', COLORS.ctv_med)
ctv_n3_60 = ROI.ROI('CTVn3_60', 'Ctv', COLORS.ctv_med)
ctv_n4_60 = ROI.ROI('CTVn4_60', 'Ctv', COLORS.ctv_med)
ctv_sb_60 = ROI.ROI('CTVsb_60', 'Ctv', COLORS.ctv_med)
ptv_p_60 =ROI.ROI('PTVp_60', 'Ptv', COLORS.ptv_med_2)
ptv_n_60 =ROI.ROI('PTVn_60', 'Ptv', COLORS.ptv_med_2)
ptv_sb_60 =ROI.ROI('PTVsb_60', 'Ptv', COLORS.ptv_med_2)
# 54
ctv_e_54 = ROI.ROI('CTVe_54','Ctv', COLORS.ctv_low_2)
ptv_e_54 = ROI.ROI('PTVe_54','Ptv',COLORS.ptv_med)
ptv_e_l_54 = ROI.ROI('PTVe_L_54','Ptv',COLORS.ptv_med)
ptv_e_r_54 = ROI.ROI('PTVe_R_54','Ptv',COLORS.ptv_med)
# 50
ctv_e_50 = ROI.ROI('CTVe_50','Ctv', COLORS.ctv_low_2)
ptv_e_50 = ROI.ROI('PTVe_50','Ptv',COLORS.ptv_med)

# Øsofagus
ctv_e_46 = ROI.ROI('CTVe_46','Ctv', COLORS.ctv_low_2)
# CTV 50
ictv_50 = ROI.ROI('ICTV_50', 'Ctv', COLORS.ctv_low)
ictv_p_50 = ROI.ROI('ICTVp_50', 'Ctv', COLORS.ctv_high_2)
ctv_n_50 =ROI.ROI('CTVn_50', 'Ctv', COLORS.ctv_med_2)
ctv_n1_50 =ROI.ROI('CTVn1_50', 'Ctv', COLORS.ctv_med_2)
ctv_n2_50 =ROI.ROI('CTVn2_50', 'Ctv', COLORS.ctv_med_2)
ctv_n3_50 =ROI.ROI('CTVn3_50', 'Ctv', COLORS.ctv_med_2)
ictv_n_50 =ROI.ROI('ICTVn_50', 'Ctv', COLORS.ctv_med_2)
ictv_n1_50 =ROI.ROI('ICTVn1_50', 'Ctv', COLORS.ctv_med_2)
ictv_n2_50 =ROI.ROI('ICTVn2_50', 'Ctv', COLORS.ctv_med_2)
ictv_n3_50 =ROI.ROI('ICTVn3_50', 'Ctv', COLORS.ctv_med_2)
ptv_50 = ROI.ROI('PTV_50', 'Ptv', COLORS.ptv_low)
ctv_50 = ROI.ROI('CTV_50', 'Ctv', COLORS.ctv_high)
# CTV 60
ctv_60 = ROI.ROI('CTV_60', 'Ctv', COLORS.ctv_low)
ictv_60 = ROI.ROI('ICTV_60', 'Ctv', COLORS.ctv_low)
ictv_p_60 = ROI.ROI('ICTVp_60', 'Ctv', COLORS.ctv_high_2)
ctv_n1_60 =ROI.ROI('CTVn1_60', 'Ctv', COLORS.ctv_med_2)
ctv_n2_60 =ROI.ROI('CTVn2_60', 'Ctv', COLORS.ctv_med_2)
ctv_n3_60 =ROI.ROI('CTVn3_60', 'Ctv', COLORS.ctv_med_2)
ictv_n_60 =ROI.ROI('ICTVn_60', 'Ctv', COLORS.ctv_med_2)
ictv_n1_60 =ROI.ROI('ICTVn1_60', 'Ctv', COLORS.ctv_med_2)
ictv_n2_60 =ROI.ROI('ICTVn2_60', 'Ctv', COLORS.ctv_med_2)
ictv_n3_60 =ROI.ROI('ICTVn3_60', 'Ctv', COLORS.ctv_med_2)
# CTV 66
ctv_n_66 =ROI.ROI('CTVn_66', 'Ctv', COLORS.ctv_med_2)
ctv_n1_66 =ROI.ROI('CTVn1_66', 'Ctv', COLORS.ctv_med_2)
ctv_n2_66 =ROI.ROI('CTVn2_66', 'Ctv', COLORS.ctv_med_2)
ctv_n3_66 =ROI.ROI('CTVn3_66', 'Ctv', COLORS.ctv_med_2)
ictv_n_66 =ROI.ROI('ICTVn_66', 'Ctv', COLORS.ctv_med_2)
ictv_n1_66 =ROI.ROI('ICTVn1_66', 'Ctv', COLORS.ctv_med_2)
ictv_n2_66 =ROI.ROI('ICTVn2_66', 'Ctv', COLORS.ctv_med_2)
ictv_n3_66 =ROI.ROI('ICTVn3_66', 'Ctv', COLORS.ctv_med_2)
ctv_p_66 = ROI.ROI('CTVp_66', 'Ctv', COLORS.ctv_high_2)
ictv_p_66 = ROI.ROI('ICTVp_66', 'Ctv', COLORS.ctv_high_2)
ctv_66 = ROI.ROI('CTV_66', 'Ctv', COLORS.ctv_low)
ictv_66 = ROI.ROI('ICTV_66', 'Ctv', COLORS.ctv_low)
# ITV
itv_46 = ROI.ROI('ITV_46','Ptv',COLORS.itv_low)
itv_46_5 = ROI.ROI('ITV_46.5','Ptv',COLORS.itv_low)
itv_50 = ROI.ROI('ITV_50','Ptv',COLORS.itv)
itv_60 = ROI.ROI('ITV_60','Ptv',COLORS.itv)
itv_66 = ROI.ROI('ITV_60','Ptv',COLORS.itv)
itv = ROI.ROI('ITV','Ptv',COLORS.itv)
# PTV
ptv_e_46 = ROI.ROI('PTVe_46','Ptv',COLORS.ptv_med)
ptv_n_66 =ROI.ROI('PTVn_66', 'Ptv', COLORS.ptv_med_2)
ptv_p_66 = ROI.ROI('PTVp_66', 'Ptv', COLORS.ptv_high_2)
ptv_66 = ROI.ROI('PTV_66','Ptv',COLORS.ptv_low)

# Breast
ptv_n_imn = ROI.ROI('PTVn_IMN', 'Ptv', COLORS.ptv_high)
ptv_n_imn_r = ROI.ROI('PTVn_IMN_R', 'Ptv', COLORS.ptv_high)
ptv_n_imn_l = ROI.ROI('PTVn_IMN_L', 'Ptv', COLORS.ptv_high)
ptv_boost = ROI.ROI('PTVpc_56', 'Ptv', COLORS.ptv)
ptv_boost_r = ROI.ROI('PTVpc_56_R', 'Ptv', COLORS.ptv)
ptv_boost_l = ROI.ROI('PTVpc_56_L', 'Ptv', COLORS.ptv)
ptv_pc =  ROI.ROI('PTVpc', 'Ptv', COLORS.x_ptv_54)
ptv_pc_l =  ROI.ROI('PTVpc_L', 'Ptv', COLORS.x_ptv_54)
ptv_pc_r =  ROI.ROI('PTVpc_R', 'Ptv', COLORS.x_ptv_54)
ptv_nc_l =  ROI.ROI('PTVnc_L', 'Ptv', COLORS.ptv)
ptv_nc_r =  ROI.ROI('PTVnc_R', 'Ptv', COLORS.ptv)
ptv_nc =  ROI.ROI('PTVnc', 'Ptv', COLORS.ptv)

# Prostate
prostate_MR = ROI.ROI('Prostate_MR', 'Ctv', COLORS.ctv_low)
ctv_p1_77 = ROI.ROI('CTVp1_77', 'Ctv', COLORS.ctv_high)
ctv_p2_70 = ROI.ROI('CTVp2_70', 'Ctv', COLORS.ctv_med_2)
#ctv_n_70 = ROI.ROI('CTVn_70', 'Ctv', COLORS.ctv_med_3)
ctv_sb_70 = ROI.ROI('CTVsb_70', 'Ctv', COLORS.ctv_high)
ctv_p1_60 = ROI.ROI('CTVp1_60', 'Ctv', COLORS.ctv_high)
ctv_p2_57 = ROI.ROI('CTVp2_57', 'Ctv', COLORS.ctv_med_2)
ctv_60 = ROI.ROI('CTV_60', 'Ctv', COLORS.ctv_low)
ctv_e_56 = ROI.ROI('CTVe_56','Ctv', COLORS.ctv_med)
ptv_p1_77 = ROI.ROI('PTVp1_77', 'Ptv', COLORS.ptv_high)
ptv_p2_70 = ROI.ROI('PTVp2_70', 'Ptv', COLORS.ptv_med)
ptv_n_70 = ROI.ROI('PTVn_70', 'Ptv', COLORS.ptv_med)
ptv_sb_70 = ROI.ROI('PTVsb_70', 'Ptv', COLORS.ptv_med)
ptv_p1_60 = ROI.ROI('PTVp1_60', 'Ptv', COLORS.ptv_high)
ptv_p2_57 = ROI.ROI('PTVp2_57', 'Ptv', COLORS.ptv_med)
ptv_60 = ROI.ROI('PTV_60', 'Ptv', COLORS.ptv_low)
ptv_e_56 = ROI.ROI('PTVe_56', 'Ptv', COLORS.ptv_low)
ptv_n_70 = ROI.ROI('PTVn_70', 'Ptv', COLORS.ptv_high_2) #er det denne som brukes?
#Prostata 2.7Gy x 20 til 67.5 Gy:
ptv_p1_67_5 = ROI.ROI('PTVp1_67.5', 'Ptv', COLORS.ptv_high)
ptv_p2_62_5 = ROI.ROI('PTVp2_62.5', 'Ptv', COLORS.ptv_med)
ctv_p1_67_5 = ROI.ROI('CTVp1_67.5', 'Ctv', COLORS.ctv_high)
ctv_p2_62_5 = ROI.ROI('CTVp2_62.5', 'Ctv', COLORS.ctv_med_2)
ptv_n_62_5 = ROI.ROI('PTVn_62.5', 'Ptv', COLORS.ptv_med)
ctv_n_62_5 = ROI.ROI('CTVn_62.5', 'Ctv', COLORS.ctv_med_3)
ctv_n1_62_5 = ROI.ROI('CTVn1_62.5', 'Ptv', COLORS.ctv_med_3)
ctv_n2_62_5 = ROI.ROI('CTVn2_62.5', 'Ctv', COLORS.ctv_med_3)
ctv_n3_62_5 = ROI.ROI('CTVn3_62.5', 'Ctv', COLORS.ctv_med_3)
#ctv_72_5 = ROI.ROI('CTV_72.5', 'Ctv', COLORS.ctv_high) #intraprostatisk boost; ikkje enno
#ptv_72_5 = ROI.ROI('PTV_72.5', 'Ptv', COLORS.ptv_high) #intraprostatisk boost; ikkje enno
# Gyn
# Gyn vulva
ctv_ln_l = ROI.ROI('CTVe_LN_L','Ctv', COLORS.ctv_low_2)
ctv_ln_r = ROI.ROI('CTVe_LN_R','Ctv', COLORS.ctv_low_2)
ctv_e_ing_l = ROI.ROI('CTVe_Ing_L','Ctv', COLORS.ctv_low_2)
ctv_e_ing_r = ROI.ROI('CTVe_Ing_R','Ctv', COLORS.ctv_low_2)
ptv_30 = ROI.ROI('PTV_30','Ptv',COLORS.ptv_med)
ptv_e_pelvic = ROI.ROI('PTVe_Pelvic','Ptv',COLORS.ptv_med)
ctv_e_pelvic = ROI.ROI('CTVe_Pelvic','Ctv', COLORS.ctv_low_2)
# 45
ctv_45 = ROI.ROI('CTV_45','Ctv', COLORS.ctv_low_2)
ctv_e_45 = ROI.ROI('CTVe_45','Ctv', COLORS.ctv_low_2)
ctv_e_pelvic_45 = ROI.ROI('CTVe_Pelvic_45','Ctv', COLORS.ctv_low_2)
ctv_p_45 = ROI.ROI('CTVp_45', 'Ctv', COLORS.ctv_med)
ctv_e_ing_l_45 = ROI.ROI('CTVe_Ing_L_45','Ctv', COLORS.ctv_low_2)
ctv_e_ing_r_45 = ROI.ROI('CTVe_Ing_R_45','Ctv', COLORS.ctv_low_2)
ptv_e_ing_45 = ROI.ROI('PTVe_Ing_45','Ptv', COLORS.ptv_low)
ptv_e_pelvic_45 = ROI.ROI('PTVe_Pelvic_45','Ptv',COLORS.ptv_med)
ptv_e_45 = ROI.ROI('PTVe_45','Ptv',COLORS.ptv_med)
ptv_p_45 = ROI.ROI('PTVp_45', 'Ptv', COLORS.ptv_med_2) #endre farge
ptv_45 = ROI.ROI('PTV_45','Ptv',COLORS.ptv_med)
# 48
ctv_e_ing_l_48 = ROI.ROI('CTVe_Ing_L_47.6','Ctv', COLORS.ctv_low_2)
ctv_e_ing_r_48 = ROI.ROI('CTVe_Ing_R_47.6','Ctv', COLORS.ctv_low_2)
ctv_e_48 = ROI.ROI('CTVe_47.6','Ctv', COLORS.ctv_low_2)
ctv_e_pelvic_48 = ROI.ROI('CTVe_Pelvic_47.6','Ctv', COLORS.ctv_low_2)
ptv_e_ing_48 = ROI.ROI('PTVe_Ing_47.6','Ptv', COLORS.ptv_low)
ptv_e_48 = ROI.ROI('PTVe_47.6','Ptv',COLORS.ptv_med)
ptv_e_pelvic_48 = ROI.ROI('PTVe_Pelvic_47.6','Ptv',COLORS.ptv_med)
# 59
ctv_n_pelvic_59 = ROI.ROI('CTVn_Pelvic_58.8', 'Ctv', COLORS.ctv_med)
ctv_n1_pelvic_59 = ROI.ROI('CTVn1_Pelvic_58.8', 'Ctv', COLORS.ctv_med)
ctv_n2_pelvic_59 = ROI.ROI('CTVn2_Pelvic_58.8', 'Ctv', COLORS.ctv_med)
ctv_n3_pelvic_59 = ROI.ROI('CTVn3_Pelvic_58.8', 'Ctv', COLORS.ctv_med)
ctv_n4_pelvic_59 = ROI.ROI('CTVn4_Pelvic_58.8', 'Ctv', COLORS.ctv_med)
ctv_n5_pelvic_59 = ROI.ROI('CTVn5_Pelvic_58.8', 'Ctv', COLORS.ctv_med)
ptv_n_pelvic_59 =ROI.ROI('PTVn_Pelvic_58.8', 'Ptv', COLORS.ptv_med_2)
ctv_n_59 = ROI.ROI('CTVn_58.8', 'Ctv', COLORS.ctv_med)
ctv_n1_59 = ROI.ROI('CTVn1_58.8', 'Ctv', COLORS.ctv_med)
ctv_n2_59 = ROI.ROI('CTVn2_58.8', 'Ctv', COLORS.ctv_med)
ctv_n3_59 = ROI.ROI('CTVn3_58.8', 'Ctv', COLORS.ctv_med)
ctv_n4_59 = ROI.ROI('CTVn4_58.8', 'Ctv', COLORS.ctv_med)
ctv_n5_59 = ROI.ROI('CTVn5_58.8', 'Ctv', COLORS.ctv_med)
ptv_n_59 =ROI.ROI('PTVn_58.8', 'Ptv', COLORS.ptv_med_2)
# 64
ctv_n_ing_64 = ROI.ROI('CTVn_Ing_64.4','Ctv', COLORS.ctv_high_2)
ctv_n_64 = ROI.ROI('CTVn_64.4','Ctv', COLORS.ctv_high_2)
ctv_n1_ing_64 = ROI.ROI('CTVn1_Ing_64.4','Ctv', COLORS.ctv_high_2)
ctv_n2_ing_64 = ROI.ROI('CTVn2_Ing_64.4','Ctv', COLORS.ctv_high_2)
ctv_n3_ing_64 = ROI.ROI('CTVn3_Ing_64.4','Ctv', COLORS.ctv_high_2)
ctv_n4_ing_64 = ROI.ROI('CTVn4_Ing_64.4','Ctv', COLORS.ctv_high_2)
ctv_n5_ing_64 = ROI.ROI('CTVn5_Ing_64.4','Ctv', COLORS.ctv_high_2)
ctv_n1_64 = ROI.ROI('CTVn1_64.4','Ctv', COLORS.ctv_high_2)
ctv_n2_64 = ROI.ROI('CTVn2_64.4','Ctv', COLORS.ctv_high_2)
ctv_n3_64 = ROI.ROI('CTVn3_64.4','Ctv', COLORS.ctv_high_2)
ctv_n4_64 = ROI.ROI('CTVn4_64.4','Ctv', COLORS.ctv_high_2)
ctv_n5_64 = ROI.ROI('CTVn5_64.4','Ctv', COLORS.ctv_high_2)
ptv_n_ing_64 = ROI.ROI('PTVn_Ing_64.4','Ptv', COLORS.ptv_low)
ptv_n_64 = ROI.ROI('PTVn_64.4','Ptv', COLORS.ptv_low)
# 67
ctv_p_67 = ROI.ROI('CTVp_67.2', 'Ctv', COLORS.ctv_med)
ptv_p_67 = ROI.ROI('PTVp_67.2', 'Ptv', COLORS.ptv_med_2)
# Gyn Cervix
ctv_n_55 = ROI.ROI('CTVn_55', 'Ctv', COLORS.ctv_med)
ctv_n1_55 = ROI.ROI('CTVn1_55', 'Ctv', COLORS.ctv_med)
ctv_n2_55 = ROI.ROI('CTVn2_55', 'Ctv', COLORS.ctv_med)
ctv_n3_55 = ROI.ROI('CTVn3_55', 'Ctv', COLORS.ctv_med)
ctv_n4_55 = ROI.ROI('CTVn4_55', 'Ctv', COLORS.ctv_med)
ctv_n5_55 = ROI.ROI('CTVn5_55', 'Ctv', COLORS.ctv_med)
ctv_n_57 = ROI.ROI('CTVn_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_sb_57 = ROI.ROI('CTVsb_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_n1_57 = ROI.ROI('CTVn1_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_n2_57 = ROI.ROI('CTVn2_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_n3_57 = ROI.ROI('CTVn3_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_n4_57 = ROI.ROI('CTVn4_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_n5_57 = ROI.ROI('CTVn5_57.5', 'Ctv', COLORS.ctv_high_2)
ptv_n_55 =ROI.ROI('PTVn_55', 'Ptv', COLORS.ptv_med_2)
ptv_n1_55 =ROI.ROI('PTVn1_55', 'Ptv', COLORS.ptv_med_2)
ptv_n2_55 =ROI.ROI('PTVn2_55', 'Ptv', COLORS.ptv_med_2)
ptv_n3_55 =ROI.ROI('PTVn3_55', 'Ptv', COLORS.ptv_med_2)
ptv_n4_55 =ROI.ROI('PTVn4_55', 'Ptv', COLORS.ptv_med_2)
ptv_n5_55 =ROI.ROI('PTVn5_55', 'Ptv', COLORS.ptv_med_2)
ptv_n_57 =ROI.ROI('PTVn_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_n1_57 =ROI.ROI('PTVn1_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_n2_57 =ROI.ROI('PTVn2_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_n3_57 =ROI.ROI('PTVn3_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_n4_57 =ROI.ROI('PTVn4_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_n5_57 =ROI.ROI('PTVn5_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_sb_57 =ROI.ROI('PTVsb_57.5', 'Ptv', COLORS.ptv_high_2)

# Rectum
ctv_n_50 =ROI.ROI('CTVn_50', 'Ctv', COLORS.ctv_med_2)
ctv_n1_50 =ROI.ROI('CTVn1_50', 'Ctv', COLORS.ctv_med_2)
ctv_n2_50 =ROI.ROI('CTVn2_50', 'Ctv', COLORS.ctv_med_2)
ctv_n3_50 =ROI.ROI('CTVn3_50', 'Ctv', COLORS.ctv_med_2)
ctv_n4_50 =ROI.ROI('CTVn4_50', 'Ctv', COLORS.ctv_med_2)
ptv_n_50 =ROI.ROI('PTVn_50', 'Ptv', COLORS.ptv_med_2)
ctv_e_ing_l_46 = ROI.ROI('CTVe_Ing_L_46.5','Ctv', COLORS.ctv_low_2)
ctv_e_ing_r_46 = ROI.ROI('CTVe_Ing_R_46.5','Ctv', COLORS.ctv_low_2)
ptv_e_ing_r_46 = ROI.ROI('PTVe_Ing_R_46.5','Ptv', COLORS.ptv_low)
ptv_e_ing_l_46 = ROI.ROI('PTVe_Ing_L_46.5','Ptv', COLORS.ptv_low)
ptv_e_ing_46 = ROI.ROI('PTVe_Ing_46.5','Ptv', COLORS.ptv_low)
ctv_e_pelvic_46_5 = ROI.ROI('CTVe_Pelvic_46.5','Ctv', COLORS.ctv_low_2)
ptv_e_pelvic_46_5 = ROI.ROI('PTVe_Pelvic_46.5','Ptv',COLORS.ptv_med)
ctv_e_46_5 = ROI.ROI('CTVe_46.5','Ctv', COLORS.ctv_low_2)
ptv_e_46_5 = ROI.ROI('PTVe_46.5','Ptv',COLORS.ptv_med)
ptv_46_5 = ROI.ROI('PTV_46.5','Ptv',COLORS.ptv_low)
ctv_sb = ROI.ROI('CTVsb', 'Ctv', COLORS.ctv_high_2)
ptv_sb = ROI.ROI('PTVsb', 'Ptv', COLORS.ptv_high_2)
ctv_e_ing_l = ROI.ROI('CTVe_Ing_L','Ctv', COLORS.ctv_low_2)
ctv_e_ing_r = ROI.ROI('CTVe_Ing_R','Ctv', COLORS.ctv_low_2)
ptv_e_ing = ROI.ROI('PTVe_Ing','Ptv', COLORS.ptv_low)
ctv_e_pelvic = ROI.ROI('CTVe_Pelvic','Ctv', COLORS.ctv_low_2)
ptv_e_pelvic = ROI.ROI('PTVe_Pelvic','Ptv',COLORS.ptv_med)

# Anus
ctv_e_pelvic_41 = ROI.ROI('CTVe_Pelvic_41.6','Ctv', COLORS.ctv_low_2)
ptv_e_pelvic_41 = ROI.ROI('PTVe_Pelvic_41.6','Ptv',COLORS.ptv_med)
ctv_p_50 = ROI.ROI('CTVp_50', 'Ctv', COLORS.ctv_high_2)
ptv_p_50 = ROI.ROI('PTVp_50', 'Ptv', COLORS.ptv_high_2)
ctv_p_54 = ROI.ROI('CTVp_54', 'Ctv', COLORS.ctv_high_2)
ptv_p_54 = ROI.ROI('PTVp_54', 'Ptv', COLORS.ptv_high_2)
ctv_p_57 = ROI.ROI('CTVp_57.5', 'Ctv', COLORS.ctv_high_2)
ptv_p_57 = ROI.ROI('PTVp_57.5', 'Ptv', COLORS.ptv_high_2)
ctv_n_54 =ROI.ROI('CTVn_54', 'Ctv', COLORS.ctv_med_2)
ptv_n_54 =ROI.ROI('PTVn_54', 'Ptv', COLORS.ptv_med_2)
ctv_n1_54 =ROI.ROI('CTVn1_54', 'Ctv', COLORS.ctv_med_2)
ptv_n1_54 =ROI.ROI('PTVn1_54', 'Ptv', COLORS.ptv_med_2)
ctv_n2_54 =ROI.ROI('CTVn2_54', 'Ctv', COLORS.ctv_med_2)
ptv_n2_54 =ROI.ROI('PTVn2_54', 'Ptv', COLORS.ptv_med_2)
ctv_n3_54 =ROI.ROI('CTVn3_54', 'Ctv', COLORS.ctv_med_2)
ptv_n3_54 =ROI.ROI('PTVn3_54', 'Ptv', COLORS.ptv_med_2)
ctv_n4_54 =ROI.ROI('CTVn4_54', 'Ctv', COLORS.ctv_med_2)
ptv_n4_54 =ROI.ROI('PTVn4_54', 'Ptv', COLORS.ptv_med_2)
ctv_e_ing_l_41 = ROI.ROI('CTVe_Ing_L_41.6','Ctv', COLORS.ctv_low)
ctv_e_ing_r_41 = ROI.ROI('CTVe_Ing_R_41.6','Ctv', COLORS.ctv_low)
ptv_e_ing_r_41 = ROI.ROI('PTVe_Ing_R_41.6','Ptv', COLORS.ptv_low)
ptv_e_ing_l_41 = ROI.ROI('PTVe_Ing_L_41.6','Ptv', COLORS.ptv_low)
ptv_e_ing_41 = ROI.ROI('PTVe_Ing_41.6','Ptv', COLORS.ptv_low)
ptv_41 = ROI.ROI('PTV_41.6','Ptv', COLORS.ptv_med)
ctv_41 = ROI.ROI('CTV_41.6','Ctv', COLORS.ctv_low_2)
ctv_e = ROI.ROI('CTVe','Ctv', COLORS.ctv_low_2)
ptv_e = ROI.ROI('PTVe','Ptv',COLORS.ptv_med)


# OARs: Empty (will be delineated manually):
# Head/Brain:
eye_l_empty = ROI.ROI('Eye_L', 'Organ', COLORS.eye)
eye_r_empty = ROI.ROI('Eye_R', 'Organ', COLORS.eye)
lens_l_empty = ROI.ROI('Lens_L', 'Organ', COLORS.lens_l)
lens_r_empty = ROI.ROI('Lens_R', 'Organ', COLORS.lens)
optic_nrv_l_empty = ROI.ROI('OpticNerve_L', 'Organ', COLORS.optic_nrv_l)
optic_nrv_r_empty = ROI.ROI('OpticNerve_R', 'Organ', COLORS.optic_nrv)
optic_chiasm_empty = ROI.ROI('OpticChiasm','Organ', COLORS.chiasma)
lacrimal_l =ROI.ROI('LacrimalGland_L', 'Organ', COLORS.lacrimal_l)
lacrimal_r =ROI.ROI('LacrimalGland_R', 'Organ', COLORS.lacrimal)
cochlea_l = ROI.ROI('Cochlea_L','Organ', COLORS.cochlea_l)
cochlea_r = ROI.ROI('Cochlea_R','Organ', COLORS.cochlea)
hippocampus_l = ROI.ROI('Hippocampus_L','Organ', COLORS.hippocampus_l)
hippocampus_r = ROI.ROI('Hippocampus_R','Organ', COLORS.hippocampus)
brainstem = ROI.ROI('Brainstem', 'Organ', COLORS.brainstem)
nasal_cavity = ROI.ROI('NasalCavity', 'Organ', COLORS.nasal_cavity)
cornea_l = ROI.ROI('Cornea_L', 'Organ', COLORS.cornea_l) 
cornea_r = ROI.ROI('Cornea_R', 'Organ', COLORS.cornea)
retina_l = ROI.ROI('Retina_L', 'Organ', COLORS.retina_l) 
retina_r = ROI.ROI('Retina_R', 'Organ', COLORS.retina)
brainstem_core = ROI.ROIExpanded('BrainstemCore', 'Organ', COLORS.brainstem_core, brainstem, margins = MARGINS.brainstem_2mm_contraction)
brainstem_surface = ROI.ROIAlgebra('BrainstemSurface', 'Organ', COLORS.brainstem_surface, sourcesA = [brainstem], sourcesB = [brainstem_core], operator = 'Subtraction')
# Head and Neck
a_carotid_l_empty =  ROI.ROI('A_Carotid_L', 'Organ', COLORS.carotid)
a_carotid_r =  ROI.ROI('A_Carotid_R', 'Organ', COLORS.carotid)
pituitary_empty = ROI.ROI('Pituitary', 'Organ', COLORS.pituitary)
submand_l = ROI.ROI('SubmandGland_L', 'Organ', COLORS.submand_l)
submand_r = ROI.ROI('SubmandGland_R', 'Organ', COLORS.submand)
parotid_l = ROI.ROI('Parotid_L', 'Organ', COLORS.parotid)
parotid_r = ROI.ROI('Parotid_R', 'Organ', COLORS.parotid_r)
oral_cavity_empty = ROI.ROI('OralCavity','Organ', COLORS.liver)
pharynx_constr_s = ROI.ROI('PharynxConstr_S','Organ', COLORS.constr_s)
pharynx_constr_m = ROI.ROI('PharynxConstr_M','Organ', COLORS.constr_m)
pharynx_constr_i = ROI.ROI('PharynxConstr_I','Organ', COLORS.constr_i)
cricopharyngeus = ROI.ROI('Cricopharyngeus','Organ', COLORS.cricopharyngeus)
eim = ROI.ROI('EsophagusInlet','Organ', COLORS.eim)
esophagus_cerv = ROI.ROI('EsophagusS','Organ', COLORS.ce)
tongue_base = ROI.ROI('TongueBase','Organ', COLORS.tongue_base)
larynx_sg_empty = ROI.ROI('Larynx_SG','Organ', COLORS.larynx_sg)
larynx_g_empty = ROI.ROI('Larynx_G','Organ', COLORS.larynx_g)
svelgpakke = ROI.ROI('Full svelgpakke','Organ', COLORS.larynx_g)
#mandible = ROI.ROI('Mandible', 'Organ', COLORS.mandible)
# Thorax:
esophagus_empty = ROI.ROI('Esophagus', 'Organ', COLORS.esophagus)
esophagus_ = ROI.ROI('Esophagus~', 'Organ', COLORS.esophagus)
spinal_cord = ROI.ROI('SpinalCord', 'Organ', COLORS.spinal_cord)
spinal_canal_empty = ROI.ROI('SpinalCanal', 'Organ', COLORS.spinal_canal)
heart_empty = ROI.ROI('Heart', 'Organ', COLORS.heart)
bronchus = ROI.ROI('Bronchus','Organ', COLORS.main_bronchus)
bronchus_l = ROI.ROI('Bronchus_L','Organ', COLORS.main_bronchus)
bronchus_r = ROI.ROI('Bronchus_R','Organ', COLORS.main_bronchus)
a_aorta = ROI.ROI('A_Aorta','Organ', COLORS.aorta)
brachial_plexus = ROI.ROI('BrachialPlexus','Organ',COLORS.brachial)
brachial_plexus_r = ROI.ROI('BrachialPlexus_R','Organ',COLORS.brachial)
brachial_plexus_l = ROI.ROI('BrachialPlexus_L','Organ',COLORS.brachial)
#spinal_canal = ROI.ROI('SpinalCanal', 'Organ', COLORS.spinal_canal)
#lung_l =  ROI.ROI('Lung_L', 'Organ', COLORS.lung) 
#lung_r =  ROI.ROI('Lung_R', 'Organ', COLORS.lung_r) 
# Breast:
sternum_empty = ROI.ROI('Sternum','Organ', COLORS.heart_prv)
#lad = ROI.ROI('A_LAD','Organ', COLORS.lad)
a_lad_empty = ROI.ROI('A_LAD','Organ', COLORS.lad)
humeral_l_empty = ROI.ROI('HumeralHead_L', 'Organ', COLORS.heart_prv)
humeral_r_empty = ROI.ROI('HumeralHead_R', 'Organ', COLORS.heart_prv)
thyroid_empty = ROI.ROI('ThyroidGland', 'Organ', COLORS.thyroid)
# Lung, stereotactic:

lung_r_igtv = ROI.ROI('Lung_R-IGTV','Organ', COLORS.lung_r)
lung_l_igtv = ROI.ROI('Lung_L-IGTV','Organ', COLORS.lung)
lung_r_gtv = ROI.ROI('Lung_R-GTV','Organ', COLORS.lung_r)
lung_l_gtv = ROI.ROI('Lung_L-GTV','Organ', COLORS.lung)
chestwall = ROI.ROI('Chestwall', 'Organ', COLORS.chestwall)
great_vessel = ROI.ROI('GreatVessel','Organ', COLORS.aorta)
great_vessels = ROI.ROI('GreatVessels','Organ', COLORS.aorta)
trachea_empty = ROI.ROI('Trachea','Organ', COLORS.trachea)
trachea_ = ROI.ROI('Trachea~','Organ', COLORS.trachea)
bronchus_ = ROI.ROI('Bronchus~','Organ', COLORS.main_bronchus)
stomach_empty = ROI.ROI('Stomach','Organ', COLORS.stomach)
liver_empty = ROI.ROI('Liver','Organ', COLORS.liver)
rib_x_l = ROI.ROI('Ribx_L','Organ', COLORS.rib)
rib_x_r = ROI.ROI('Ribx_R','Organ', COLORS.rib)
rib_y_l = ROI.ROI('Riby_L','Organ', COLORS.rib)
rib_y_r = ROI.ROI('Riby_R','Organ', COLORS.rib)
ribs = ROI.ROI('Ribs','Organ', COLORS.ribs)
main_bronchus_l = ROI.ROI('BronchusMain_L','Organ', COLORS.main_bronchus)
main_bronchus_r = ROI.ROI('BronchusMain_R','Organ', COLORS.main_bronchus)
connective_tissue =ROI.ROI('ConnectiveTissue','Organ', COLORS.bladder)
mediastinum = ROI.ROI('Mediastinum','Organ',COLORS.z_psv_green)
# Abdomen
kidney_l_empty = ROI.ROI('Kidney_L', 'Organ', COLORS.kidney)
kidney_r_empty = ROI.ROI('Kidney_R', 'Organ', COLORS.kidney_l)
# Spine SBRT:
cauda_equina = ROI.ROI('CaudaEquina','Organ', COLORS.cauda)
bowel_small= ROI.ROI('BowelSmall','Organ', COLORS.small_bowel)
bowel_large = ROI.ROI('BowelLarge','Organ', COLORS.bowel_bag)
colon = ROI.ROI('Colon','Organ', COLORS.colon)
brachial = ROI.ROI('BrachialPlexus','Organ', COLORS.brachial)
duodenum =  ROI.ROI('Duodenum','Organ', COLORS.duodenum)
sacral_plexus = ROI.ROI('SacralPlexus','Organ',COLORS.sacral)
nerve_root = ROI.ROI('NerveRoot','Organ',COLORS.nerve_root)
nerve_peripheral = ROI.ROI('NervePeripheral','Organ',COLORS.nerve_peripheral)
nerve_root1_l = ROI.ROI('NerveRoot1_L','Organ',COLORS.nerve_root)
nerve_root2_l = ROI.ROI('NerveRoot2_L','Organ',COLORS.nerve_root)
nerve_root1_r = ROI.ROI('NerveRoot1_R','Organ',COLORS.nerve_root)
nerve_root2_r = ROI.ROI('NerveRoot2_R','Organ',COLORS.nerve_root)
bile_duct = ROI.ROI('BileDuct_Common','Organ', COLORS.bile_duct)
ureter = ROI.ROI('Ureter','Organ', COLORS.liver)
# Liver SBRT:
spleen_empty = ROI.ROI('Spleen', 'Organ', COLORS.spleen)
bile_drain = ROI.ROI('Bile_Drain', 'Organ', COLORS.bile_drain)
gall_bladder = ROI.ROI('GallBladder', 'Organ', COLORS.bile_drain)
# Pelvis
bowel_bag = ROI.ROI('BowelBag', 'Organ', COLORS.bowel_bag)
bowel_space = ROI.ROI('BowelBag', 'Organ', COLORS.bowel_space)
rectum = ROI.ROI('Rectum', 'Organ', COLORS.rectum)
bladder = ROI.ROI('Bladder', 'Organ', COLORS.bladder)
# Gyn
sigmoid = ROI.ROI('Sigmoid','Organ', COLORS.penile_bulb)
ovary_r = ROI.ROI('Ovary_R','Organ', COLORS.ovary)
ovary_l = ROI.ROI('Ovary_L','Organ', COLORS.ovary)
# Prostate
pelvic_nodes = ROI.ROI('LN_Iliac', 'Ctv', COLORS.pelvic_nodes)
prostate = ROI.ROI('Prostate', 'Ctv', COLORS.prostate)
prostate_bed = ROI.ROI('SurgicalBed', 'Ctv', COLORS.prostate_bed)
vesicles = ROI.ROI('SeminalVes', 'Ctv', COLORS.vesicles)
anal_canal = ROI.ROI('AnalCanal','Organ', COLORS.anal_canal)
penile_bulb = ROI.ROI('PenileBulb','Organ', COLORS.penile_bulb)
genitals = ROI.ROI('Genitals','Organ', COLORS.penile_bulb)
# Skin
skin_srt = ROI.ROIWall('Skin','Organ', COLORS.skin, body, 0, 0.3)
#skin = ROI.ROIWall('Skin','Organ', COLORS.skin, body, 0, 0.5)
skin = ROI.ROIAlgebra('Skin', 'Organ', COLORS.skin, sourcesA=[body],sourcesB=[body], operator = 'Subtraction',marginsA=MARGINS.zero,marginsB = MARGINS.skin_contraction)
skin_10 = ROI.ROIAlgebra('Skin', 'Organ', COLORS.skin, sourcesA=[body],sourcesB=[body], operator = 'Subtraction',marginsA=MARGINS.zero,marginsB = MARGINS.skin_contraction_10)
skin_brain_5 = ROI.ROIWall('Skin','Organ', COLORS.skin, body, 0, 0.5)
skin_brain = ROI.ROIWall('Skin','Organ', COLORS.skin, external, 0, 0.5)
# Undefined/ other ROIs
# Breast organs:
surgical_bed = ROI.ROI('SurgicalBed','Undefined', COLORS.breast_draft)
breast_l_draft_empty = ROI.ROI('Breast_L_Draft', 'Ctv', COLORS.breast_draft)
breast_r_draft_empty = ROI.ROI('Breast_R_Draft', 'Ctv', COLORS.breast_draft)
breast_l_contralat_draft_empty = ROI.ROI('Breast_L_Draft', 'Undefined', COLORS.contralat_draft)
breast_r_contralat_draft_empty = ROI.ROI('Breast_R_Draft', 'Undefined', COLORS.contralat_draft)
breast_draft = ROI.ROI('Breast draft', 'Undefined', COLORS.breast_draft)
breast_l_empty = ROI.ROIAlgebra('Breast_L', 'Organ', COLORS.contralat, sourcesA = [breast_l_contralat_draft_empty], sourcesB = [body], operator = 'Intersection', marginsA = MARGINS.zero, marginsB = MARGINS.uniform_5mm_contraction)
breast_r_empty = ROI.ROIAlgebra('Breast_R', 'Organ', COLORS.contralat, sourcesA = [breast_r_contralat_draft_empty], sourcesB = [body], operator = 'Intersection', marginsA = MARGINS.zero, marginsB = MARGINS.uniform_5mm_contraction)

artery1_l = ROI.ROI('A_Subclavian_L', 'Undefined', COLORS.artery1)
artery2_l = ROI.ROI('A_Carotid_L', 'Undefined', COLORS.artery2)
vein1_l = ROI.ROI('V_Brachioceph+V_Subclavian_L', 'Undefined', COLORS.vein1)
vein2_l = ROI.ROI('V_Jugular_L','Undefined', COLORS.vein2)
muscle = ROI.ROI('ScaleneMusc', 'Undefined', COLORS.muscle)
artery1_r = ROI.ROI('A_Brachioceph+A_Subclavian_R', 'Undefined', COLORS.artery1)
artery2_r = ROI.ROI('A_Carotid_R', 'Undefined', COLORS.artery2)
vein1_r = ROI.ROI('V_Brachioceph+V_Subclavian_R', 'Undefined', COLORS.vein1)
vein2_r = ROI.ROI('V_Jugular_R','Undefined', COLORS.vein2)

# Prosthesis
prosthesis = ROI.ROI('Prosthesis','Undefined', COLORS.prosthesis)
prosthesis_l = ROI.ROI('Prosthesis_L','Undefined', COLORS.prosthesis)
prosthesis_r = ROI.ROI('Prosthesis_R','Undefined', COLORS.prosthesis)
icd = ROI.ROI('ICD','Undefined',COLORS.cv)
pacemaker = ROI.ROI('Pacemaker','Undefined',COLORS.cv)

# Markers:
clips = ROI.ROI('Markers', 'Marker', COLORS.clips)
markers = ROI.ROI('Markers', 'Marker', COLORS.clips)
seed1 = ROI.ROI('Marker1', 'Marker', COLORS.seed)
seed2 = ROI.ROI('Marker2', 'Marker', COLORS.seed)
seed3 = ROI.ROI('Marker3', 'Marker', COLORS.seed)
seed4 = ROI.ROI('Marker4', 'Marker', COLORS.seed)
marker1 = ROI.ROI('Marker1', 'Marker', COLORS.seed)
marker2 = ROI.ROI('Marker2', 'Marker', COLORS.seed)
marker3 = ROI.ROI('Marker3', 'Marker', COLORS.seed)
marker4 = ROI.ROI('Marker4', 'Marker', COLORS.seed)
temp_markers = ROI.ROI('tempMarkers', 'Marker', COLORS.seed)

# OARs: MBS (delineated by model based segmentation):
brain = ROI.ROI('Brain', 'Organ', COLORS.brain, case ='HeadNeck', model = 'Brain', model_type = 'MBS')
#brainstem = ROI.ROI('Brainstem', 'Organ', COLORS.brainstem, case ='HeadNeck',  model = 'Brainstem')
#spinal_canal = ROI.ROI('SpinalCanal', 'Organ', COLORS.spinal_canal, case ='Thorax',  model = 'SpinalCord (Thorax)')
spinal_canal_mbs = ROI.ROI('SpinalCanal', 'Organ', COLORS.spinal_canal, case ='HeadNeck',  model =  'SpinalCord', model_type = 'MBS')
#parotid_l = ROI.ROI('Parotid_L', 'Organ', COLORS.parotid, case ='HeadNeck',  model = 'ParotidGland (Left)')
#parotid_r = ROI.ROI('Parotid_R', 'Organ', COLORS.parotid, case ='HeadNeck',  model = 'ParotidGland (Right)')
mandible = ROI.ROI('Mandible', 'Organ', COLORS.mandible, case ='HeadNeck',  model = 'Mandible', model_type = 'MBS')
#lung_l =  ROI.ROI('Lung_L', 'Organ', COLORS.lung, case ='Thorax-Abdomen',  model =  'Lung (Left)')
#lung_r =  ROI.ROI('Lung_R', 'Organ', COLORS.lung_r, case ='Thorax',  model = 'Lung (Right)')
#kidney_l = ROI.ROI('Kidney_L', 'Organ', COLORS.kidney, case ='Abdomen',  model = 'Kidney (Left)')
#kidney_r = ROI.ROI('Kidney_R', 'Organ', COLORS.kidney, case ='Abdomen',  model = 'Kidney (Right)')
#bladder = ROI.ROI('Bladder', 'Organ', COLORS.bladder, case ='PelvicMale',  model = 'Bladder')
femoral_l = ROI.ROI('FemoralHead_L', 'Organ', COLORS.femoral, case = 'PelvicMale', model = 'FemoralHead (Left)', model_type = 'MBS')
femoral_r = ROI.ROI('FemoralHead_R', 'Organ', COLORS.femoral_r, case = 'PelvicMale', model = 'FemoralHead (Right)', model_type = 'MBS')
#eye_l = ROI.ROI('Eye_L', 'Organ', COLORS.eye_l, case ='HeadNeck', model ='Eye (Left)')
#eye_r = ROI.ROI('Eye_R', 'Organ', COLORS.eye, case ='HeadNeck', model ='Eye (Right)')

# OARs: AI structures - OAR segmentation
#ctv_imn_l = ROI.ROI('CTVn_IMN_L', 'Ctv', COLORS.imn, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
#ctv_imn_r = ROI.ROI('CTVn_IMN_R', 'Ctv', COLORS.imn, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
breast_l_draft = ROI.ROI('Breast_L_Draft', 'Ctv', COLORS.breast_draft, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
breast_r_draft = ROI.ROI('Breast_R_Draft', 'Ctv', COLORS.breast_draft, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
breast_l_contralat_draft = ROI.ROI('Breast_L_Draft', 'Undefined', COLORS.contralat_draft, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
breast_r_contralat_draft = ROI.ROI('Breast_R_Draft', 'Undefined', COLORS.contralat_draft, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
ctv_n_imn_l = ROI.ROI('CTVn_IMN_L', 'Ctv', COLORS.imn, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
ctv_n_imn_r = ROI.ROI('CTVn_IMN_R', 'Ctv', COLORS.imn, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level4_l = ROI.ROI('CTVn_L4_L', 'Ctv', COLORS.level4, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level3_l = ROI.ROI('CTVn_L3_L', 'Ctv', COLORS.level3, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level2_l = ROI.ROI('CTVn_L2_L', 'Ctv', COLORS.level2, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level1_l = ROI.ROI('CTVn_L1_L', 'Ctv', COLORS.level1, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level_interpect_l = ROI.ROI('CTVn_Interpect_L', 'Ctv', COLORS.level, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level4_r = ROI.ROI('CTVn_L4_R', 'Ctv', COLORS.level4, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level3_r = ROI.ROI('CTVn_L3_R', 'Ctv', COLORS.level3, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level2_r = ROI.ROI('CTVn_L2_R', 'Ctv', COLORS.level2, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level1_r = ROI.ROI('CTVn_L1_R', 'Ctv', COLORS.level1, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
level_interpect_r = ROI.ROI('CTVn_Interpect_R', 'Ctv', COLORS.level, case ='Breast',  model =  'RSL Breast CT', model_type = 'AI')
humeral_l = ROI.ROI('HumeralHead_L', 'Organ', COLORS.humeral, case ='Breast',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')
humeral_r = ROI.ROI('HumeralHead_R', 'Organ', COLORS.humeral_r, case ='Breast',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI') #St. Olavs-Alesund Breast CT
a_carotid_l = ROI.ROI('A_Carotid_L','Undefined', COLORS.artery2, case ='Breast',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')
a_subclavian_l =  ROI.ROI('A_Subclavian_L','Undefined', COLORS.artery1, case ='Breast',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')
scalene_musc_ant_l = ROI.ROI('ScaleneMusc_Ant_L','Undefined', COLORS.muscle, case ='Breast',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')
v_branchioceph_l = ROI.ROI('V_Brachioceph_L','Undefined', COLORS.vein1, case ='Breast',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')
v_jugular_l = ROI.ROI('V_Jugular_L','Undefined', COLORS.vein2, case ='Breast',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')
v_subclavian_l =  ROI.ROI('V_Subclavian_L','Undefined', COLORS.vein3, case ='Breast',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')

pituitary = ROI.ROI('Pituitary', 'Organ', COLORS.pituitary, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
brain_head = ROI.ROI('Brain', 'Organ', COLORS.brain, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
optic_nrv_l = ROI.ROI('OpticNerve_L', 'Organ', COLORS.optic_nrv_l, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
optic_nrv_r = ROI.ROI('OpticNerve_R', 'Organ', COLORS.optic_nrv, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
optic_chiasm = ROI.ROI('OpticChiasm','Organ', COLORS.chiasma, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
eye_l = ROI.ROI('Eye_L', 'Organ', COLORS.eye, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
eye_r = ROI.ROI('Eye_R', 'Organ', COLORS.eye, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
lens_l = ROI.ROI('Lens_L', 'Organ', COLORS.lens_l, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
lens_r = ROI.ROI('Lens_R', 'Organ', COLORS.lens, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
spinal_canal = ROI.ROI('SpinalCanal', 'Organ', COLORS.spinal_canal, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')
spinal_canal_head = ROI.ROI('SpinalCanal', 'Organ', COLORS.spinal_canal, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
spinal_cord_head = ROI.ROI('SpinalCord', 'Organ', COLORS.spinal_cord, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
lips = ROI.ROI('Lips', 'Organ', COLORS.level2, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
oral_cavity = ROI.ROI('OralCavity', 'Organ', COLORS.level1, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
esophagus = ROI.ROI('Esophagus', 'Organ', COLORS.esophagus, case ='Thorax-Abdomen',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')
esophagus_head = ROI.ROI('Esophagus', 'Organ', COLORS.esophagus, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
heart = ROI.ROI('Heart', 'Organ', COLORS.heart, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')
thyroid = ROI.ROI('ThyroidGland', 'Organ', COLORS.thyroid, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')
thyroid_head = ROI.ROI('ThyroidGland', 'Organ', COLORS.thyroid, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
trachea = ROI.ROI('Trachea', 'Organ', COLORS.trachea, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')
trachea_head = ROI.ROI('Trachea', 'Organ', COLORS.trachea, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
larynx_g = ROI.ROI('Larynx_G', 'Organ', COLORS.larynx_g, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
larynx_sg = ROI.ROI('Larynx_SG', 'Organ', COLORS.larynx_sg, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
lung_l_head = ROI.ROI('Lung_L', 'Organ', COLORS.lung, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
lung_r_head = ROI.ROI('Lung_R', 'Organ', COLORS.lung_r, case ='Head and Neck',  model =  'RSL Head and Neck CT', model_type = 'AI')
sternum = ROI.ROI('Sternum','Organ', COLORS.heart_prv, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')
lad = ROI.ROI('A_LAD','Organ', COLORS.lad, case ='Thorax-Abdomen',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')
a_lad = ROI.ROI('A_LAD','Organ', COLORS.lad, case ='Thorax-Abdomen',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI')
liver = ROI.ROI('Liver','Organ', COLORS.liver, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')
lung_l =  ROI.ROI('Lung_L', 'Organ', COLORS.lung, case ='Thorax-Abdomen',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI') # ENDRE HER
lung_r =  ROI.ROI('Lung_R', 'Organ', COLORS.lung_r, case ='Thorax-Abdomen',  model =  'St. Olavs-Alesund Breast CT', model_type = 'AI') #ENDRE HER
kidney_l = ROI.ROI('Kidney_L', 'Organ', COLORS.kidney, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')
kidney_r = ROI.ROI('Kidney_R', 'Organ', COLORS.kidney, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')
spleen = ROI.ROI('Spleen', 'Organ', COLORS.spleen, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')
stomach = ROI.ROI('Stomach', 'Organ', COLORS.stomach, case ='Thorax-Abdomen',  model =  'RSL Thorax-Abdomen CT', model_type = 'AI')

# OARs: Unions:
parotids = ROI.ROIAlgebra('Parotids', 'Organ', COLORS.parotid, sourcesA=[parotid_l], sourcesB=[parotid_r])
submands = ROI.ROIAlgebra('SubmandGlands', 'Organ', COLORS.submand, sourcesA=[submand_l], sourcesB=[submand_r])
lungs =  ROI.ROIAlgebra('Lungs', 'Organ', COLORS.lungs, sourcesA=[lung_l], sourcesB=[lung_r])
kidneys =  ROI.ROIAlgebra('Kidneys', 'Organ', COLORS.kidneys, sourcesA=[kidney_l], sourcesB=[kidney_r])
ribs_l = ROI.ROIAlgebra('Ribs_L','Organ', COLORS.ribs, sourcesA=[rib_x_l], sourcesB=[rib_y_l])
ribs_r = ROI.ROIAlgebra('Ribs_R','Organ', COLORS.ribs, sourcesA=[rib_x_r], sourcesB=[rib_y_r])
lungs_igtv = ROI.ROIAlgebra('Lungs-IGTV', 'Organ', COLORS.lungs, sourcesA=[lungs], sourcesB=[igtv], operator = 'Subtraction')
liver_igtv = ROI.ROIAlgebra('Liver-IGTV', 'Organ', COLORS.liver_igtv, sourcesA=[liver], sourcesB=[igtv], operator = 'Subtraction')
liver_gtv = ROI.ROIAlgebra('Liver-GTV', 'Organ', COLORS.liver_igtv, sourcesA=[liver], sourcesB=[gtv], operator = 'Subtraction')
liver_ctv = ROI.ROIAlgebra('Liver-CTV', 'Organ', COLORS.liver_igtv, sourcesA=[liver], sourcesB=[ctv], operator = 'Subtraction')
liver_ictv = ROI.ROIAlgebra('Liver-ICTV', 'Organ', COLORS.liver_igtv, sourcesA=[liver], sourcesB=[ictv], operator = 'Subtraction')
nerve_roots = ROI.ROIAlgebra('NerveRoots','Organ',COLORS.nerve_root, sourcesA=[nerve_root2_l,nerve_root1_l], sourcesB=[nerve_root1_r,nerve_root2_r])

# OARs: Target subtracted
# Other:
other_ptv = ROI.ROI('Other_PTV', 'Organ', COLORS.other_ptv)
body_gtv = ROI.ROIAlgebra('Body-GTV', 'Undefined', COLORS.prv, sourcesA=[body], sourcesB=[gtv], operator = 'Subtraction', marginsA = MARGINS.zero, marginsB = MARGINS.zero) # JSK bytt fra 'Organ' til 'Undefined' 2023-03-02
body_ptv = ROI.ROIAlgebra('Body-PTV', 'Undefined', COLORS.prv, sourcesA=[body], sourcesB=[ptv], operator = 'Subtraction', marginsA = MARGINS.zero, marginsB = MARGINS.zero) # JSK bytt fra 'Organ' til 'Undefined' 2023-03-02
brain_gtv = ROI.ROI('Brain-GTV','Organ', COLORS.brain)
brain_ptv = ROI.ROI('Brain-PTV','Organ', COLORS.other_ptv)
lungs_gtv = ROI.ROI('Lungs-GTV', 'Organ', COLORS.lungs)
lungs_ctv = ROI.ROI('Lungs-CTV', 'Organ', COLORS.lungs)
ptv_gtv = ROI.ROI('PTV-GTV', 'Ptv', COLORS.ptv_med)
breast_l = ROI.ROIAlgebra('Breast_L', 'Organ', COLORS.contralat, sourcesA = [breast_l_contralat_draft], sourcesB = [body], operator = 'Intersection', marginsA = MARGINS.zero, marginsB = MARGINS.uniform_5mm_contraction)
breast_r = ROI.ROIAlgebra('Breast_R', 'Organ', COLORS.contralat, sourcesA = [breast_r_contralat_draft], sourcesB = [body], operator = 'Intersection', marginsA = MARGINS.zero, marginsB = MARGINS.uniform_5mm_contraction)


# PRVs:
brainstem_surface_prv = ROI.ROIAlgebra('Brainstem_Surface_PRV', 'Avoidance', COLORS.prv, sourcesA=[brainstem_surface],sourcesB=[brainstem], operator = 'Subtraction',marginsA=MARGINS.uniform_3mm_expansion,marginsB = MARGINS.zero)
spinal_canal_prv = ROI.ROIExpanded('SpinalCanal_PRV', 'Avoidance', COLORS.prv, source=spinal_canal, margins=MARGINS.uniform_3mm_expansion)
brainstem_prv = ROI.ROIExpanded('Brainstem_PRV', 'Avoidance', COLORS.prv, source=brainstem, margins=MARGINS.uniform_3mm_expansion)
retina_l_prv = ROI.ROIExpanded('Retina_L_PRV', 'Avoidance', COLORS.prv, source=retina_l, margins=MARGINS.uniform_3mm_expansion)
retina_r_prv = ROI.ROIExpanded('Retina_R_PRV', 'Avoidance', COLORS.prv, source=retina_r, margins=MARGINS.uniform_3mm_expansion)
eye_l_prv = ROI.ROIExpanded('Eye_PRV_L', 'Avoidance', COLORS.prv, source=eye_l, margins=MARGINS.uniform_3mm_expansion)
eye_r_prv = ROI.ROIExpanded('Eye_PRV_R', 'Avoidance', COLORS.prv, source=eye_r, margins=MARGINS.uniform_3mm_expansion)
lens_l_prv = ROI.ROIExpanded('Lens_PRV_L', 'Avoidance', COLORS.prv, source=lens_l, margins=MARGINS.uniform_3mm_expansion)
lens_r_prv = ROI.ROIExpanded('Lens_PRV_R', 'Avoidance', COLORS.prv, source=lens_r, margins=MARGINS.uniform_3mm_expansion)
optic_nrv_l_prv = ROI.ROIExpanded('OpticNerve_PRV_L', 'Avoidance', COLORS.prv, source=optic_nrv_l, margins=MARGINS.uniform_3mm_expansion)
optic_nrv_r_prv = ROI.ROIExpanded('OpticNerve_PRV_R', 'Avoidance', COLORS.prv, source=optic_nrv_r, margins=MARGINS.uniform_3mm_expansion)
optic_chiasm_prv = ROI.ROIExpanded('OpticChiasm_PRV','Avoidance', COLORS.prv, source=optic_chiasm, margins=MARGINS.uniform_3mm_expansion)
lacrimal_l_prv =ROI.ROIExpanded('LacrimalGland_PRV_L', 'Avoidance', COLORS.prv, source=lacrimal_l, margins=MARGINS.uniform_3mm_expansion)
lacrimal_r_prv =ROI.ROIExpanded('LacrimalGland_PRV_R', 'Avoidance', COLORS.prv, source=lacrimal_r, margins=MARGINS.uniform_3mm_expansion)
spinal_cord_prv = ROI.ROIExpanded('SpinalCord_PRV', 'Avoidance', COLORS.prv, source=spinal_cord, margins=MARGINS.uniform_3mm_expansion)
x_spinal_canal = ROI.ROIExpanded('xSpinalCanal', 'Undefined', COLORS.prv,source=spinal_canal, margins=MARGINS.uniform_5mm_expansion)
bronchus_prv = ROI.ROIExpanded('Bronchus_PRV', 'Avoidance', COLORS.prv, source=bronchus, margins=MARGINS.uniform_5mm_expansion)
trachea_prv = ROI.ROIExpanded('Trachea_PRV', 'Avoidance', COLORS.prv, source=trachea, margins=MARGINS.uniform_5mm_expansion)
esophagus_prv = ROI.ROIExpanded('Esophagus_PRV', 'Avoidance', COLORS.prv, source=esophagus, margins=MARGINS.uniform_5mm_expansion)
spinal_cord_narlal_prv = ROI.ROIExpanded('SpinalCord_PRV', 'Avoidance', COLORS.prv, source=spinal_cord, margins=MARGINS.uniform_5mm_expansion)
spinal_cord_prv_2 = ROI.ROIExpanded('SpinalCord_PRV', 'Avoidance', COLORS.prv, source=spinal_cord, margins=MARGINS.uniform_2mm_expansion)
brainstem_prv_2 = ROI.ROIExpanded('Brainstem_PRV', 'Avoidance', COLORS.prv, source=brainstem, margins=MARGINS.uniform_2mm_expansion)
heart_prv =  ROI.ROIExpanded('Heart_PRV', 'Avoidance', COLORS.heart_prv, source=heart, margins=MARGINS.uniform_5mm_expansion)
nerve_root_prv = ROI.ROIExpanded('NerveRoot_PRV', 'Avoidance', COLORS.prv, source=nerve_root, margins=MARGINS.uniform_3mm_expansion)
nerve_roots_prv = ROI.ROIExpanded('NerveRoots_PRV', 'Avoidance', COLORS.prv, source=nerve_roots, margins=MARGINS.uniform_2mm_expansion)
nerve_peripheral_prv = ROI.ROIExpanded('NervePeriph_PRV', 'Avoidance', COLORS.prv, source=nerve_peripheral, margins=MARGINS.uniform_3mm_expansion)
cauda_equina_prv = ROI.ROIExpanded('CaudaEquina_PRV', 'Avoidance', COLORS.prv, source=cauda_equina, margins=MARGINS.uniform_3mm_expansion)
sacral_plexus_prv = ROI.ROIExpanded('SacralPlexus_PRV', 'Avoidance', COLORS.prv, source=sacral_plexus, margins=MARGINS.uniform_3mm_expansion)
bowel_small_prv = ROI.ROIExpanded('BowelSmall_PRV', 'Avoidance', COLORS.prv, source=bowel_small, margins=MARGINS.uniform_5mm_expansion)
bowel_large_prv = ROI.ROIExpanded('BowelLarge_PRV', 'Avoidance', COLORS.prv, source=bowel_large, margins=MARGINS.uniform_5mm_expansion)
stomach_prv = ROI.ROIExpanded('Stomach_PRV', 'Avoidance', COLORS.prv, source=stomach, margins=MARGINS.uniform_5mm_expansion)
duodenum_prv = ROI.ROIExpanded('Duodenum_PRV', 'Avoidance', COLORS.prv, source=duodenum, margins=MARGINS.uniform_5mm_expansion)
rectum_prv = ROI.ROIExpanded('Rectum_PRV', 'Avoidance', COLORS.prv, source=rectum, margins=MARGINS.uniform_5mm_expansion)
anal_canal_prv = ROI.ROIExpanded('AnalCanal_PRV', 'Avoidance', COLORS.prv, source=anal_canal, margins=MARGINS.uniform_5mm_expansion)
esophagus_prv = ROI.ROIExpanded('Esophagus_PRV', 'Avoidance', COLORS.prv, source=esophagus, margins=MARGINS.uniform_5mm_expansion)
great_vessels_prv = ROI.ROIExpanded('GreatVessels_PRV', 'Avoidance', COLORS.prv, source=great_vessels, margins=MARGINS.uniform_5mm_expansion)
bladder_prv = ROI.ROIExpanded('Bladder_PRV', 'Avoidance', COLORS.prv, source=bladder, margins=MARGINS.uniform_5mm_expansion)

# ROIS USED FOR OPTIMIZATION

# ROIs for optimization, targets
x_gtv_p = ROI.ROI('xGTVp','Undefined',COLORS.x_gtv_p)
x_gtv_p_1 = ROI.ROI('xGTVp+1cm','Undefined',COLORS.z_psv_orange)
x_gtv_n_1 = ROI.ROI('xGTVn+0.5cm','Undefined',COLORS.z_psv_orange)
x_center_of_gtv = ROI.ROI('xCenter_of_GTV','Undefined',COLORS.wall)
x_ctv_ = ROI.ROI('xCTV!','Undefined',COLORS.x_ctv_54)
x_ctv_p = ROI.ROI('xCTVp','Undefined',COLORS.x_gtv_p)
x_ctv_e = ROI.ROI('xCTVe','Undefined',COLORS.x_ctv_54)
ctv_oars = ROI.ROI('xCTV-OARs', 'Ctv', COLORS.ctv)
ptv_oars = ROI.ROI('xPTV-OARs', 'Ptv', COLORS.ptv)
ptv_and_oars = ROI.ROI('xPTV_AND_OARs', 'Ptv', COLORS.other_ptv)
x_ptv_ = ROI.ROI('xPTV!','Undefined',COLORS.x_ptv_54)
x_ptv_lunge = ROI.ROI('xPTV_Lunge','Undefined',COLORS.x_ptv_54)
x_ptv_vev = ROI.ROI('xPTV_Vev','Undefined',COLORS.x_ptv_54)
x_ptv_n = ROI.ROI('xPTVn', 'Undefined', COLORS.ptv)
x_ptv_p = ROI.ROI('xPTVp', 'Undefined', COLORS.x_ptv_54)
x_ptv_n_l = ROI.ROI('xPTVn_L', 'Undefined', COLORS.ptv)
x_ptv_p_l = ROI.ROI('xPTVp_L', 'Undefined', COLORS.x_ptv_54)
x_ptv_n_r = ROI.ROI('xPTVn_R', 'Undefined', COLORS.ptv)
x_ptv_p_r = ROI.ROI('xPTVp_R', 'Undefined', COLORS.x_ptv_54)
x_ptv_l = ROI.ROI('xPTV_L', 'Undefined', COLORS.ptv)
x_ptv_r = ROI.ROI('xPTV_R', 'Undefined', COLORS.x_ptv_54)
x_ptv = ROI.ROI('xPTV', 'Ptv', COLORS.ptv)
x_ptv_caud = ROI.ROI('xPTVcaud', 'Undefined', COLORS.ptv)
x_ptv_cran = ROI.ROI('xPTVcran', 'Undefined', COLORS.ptv)
x_ptv_gtv =  ROI.ROI('xPTV-GTV','Undefined',COLORS.wall)
x_ptv_5 = ROI.ROI('xPTV+5cm','Undefined',COLORS.z_psv_yellow)
x_ptv_70 = ROI.ROI('xPTV!_70', 'Undefined', COLORS.ptv_med)
x_ptv_62_5 = ROI.ROI('xPTV!_62.5','Undefined',COLORS.x_ptv_60) #For prostata 2.7 Gy x 25
x_ctv_60 = ROI.ROI('xCTV!_60','Undefined',COLORS.x_ctv_60)
x_ptv_60 = ROI.ROI('xPTV!_60','Undefined',COLORS.x_ptv_60)
x_ptv_57 = ROI.ROI('xPTV!_57','Undefined',COLORS.x_ptv_60) #For prostata 3 Gy x 20
x_ctv_56 = ROI.ROI('xCTV!_56', 'Undefined', COLORS.ctv_low)
x_ptv_56 = ROI.ROI('xPTV!_56', 'Undefined', COLORS.ptv_low)
x_ctv_54 = ROI.ROI('xCTV!_54','Undefined',COLORS.x_ctv_54)
x_ptv_54 = ROI.ROI('xPTV!_54','Undefined',COLORS.x_ptv_54)
x_ctv_50 = ROI.ROI('xCTV!_50','Undefined',COLORS.x_ctv_54)
x_ptv_50 = ROI.ROI('xPTV!_50','Undefined',COLORS.x_ptv_54)
x_ctv_48 = ROI.ROI('xCTV!_47.6','Undefined',COLORS.x_ctv_54)
x_ptv_48 = ROI.ROI('xPTV!_47.6','Undefined',COLORS.x_ptv_54)
x_ctv_46_5 = ROI.ROI('xCTV!_46.5','Undefined',COLORS.x_ctv_54)
x_ptv_46_5 = ROI.ROI('xPTV!_46.5','Undefined',COLORS.x_ptv_54)
x_ctv_46 = ROI.ROI('xCTV!_46','Undefined',COLORS.x_ctv_54)
x_ptv_46 = ROI.ROI('xPTV!_46','Undefined',COLORS.x_ptv_54)
x_ctv_45 = ROI.ROI('xCTV!_45','Undefined',COLORS.x_ctv_54)
x_ptv_45 = ROI.ROI('xPTV!_45','Undefined',COLORS.x_ptv_45)
x_ptv_45_1 = ROI.ROI('xPTV!_45_1','Undefined',COLORS.x_ptv_45)
x_ctv_41 = ROI.ROI('xCTV!_41.6','Undefined',COLORS.x_ctv_54)
x_ptv_41 = ROI.ROI('xPTV!_41.6','Undefined',COLORS.x_ptv_54)
x_3_1_1_gtv_p = ROI.ROIExpanded('x3/1/1','Undefined', COLORS.cv, source=gtv_p, margins=MARGINS.esophagus_x_ctv_e_expansion)
x_3_1_1_igtv_p = ROI.ROIExpanded('x3/1/1','Undefined', COLORS.cv, source=igtv_p, margins=MARGINS.esophagus_x_ctv_e_expansion)

# OARS
x_spare_caud = ROI.ROI('xSpareCaud', 'Undefined', COLORS.x_spare_caud)
x_spare_mid = ROI.ROI('xSpareMid', 'Undefined', COLORS.x_spare_mid)
x_spare_cran = ROI.ROI('xSpareCran', 'Undefined', COLORS.x_spare_cran)
x_parotid_l = ROI.ROI('xParotid_L', 'Undefined', COLORS.x_parotid_l)
x_parotid_r = ROI.ROI('xParotid_R', 'Undefined', COLORS.x_parotid_r)
x_oral_cavity = ROI.ROI('xOralCavity', 'Undefined', COLORS.x_oral_cavity)
x_submand_l = ROI.ROI('xSubmandGland_L', 'Undefined', COLORS.x_submand_l)
x_submand_r = ROI.ROI('xSubmandGland_R', 'Undefined', COLORS.x_submand_r)
x_bladder = ROI.ROI('xBladder','Undefined', COLORS.bladder)
x_bowelbag = ROI.ROI('xBowelBag','Undefined', COLORS.bowel_space)
x_genitals = ROI.ROI('xGenitals','Undefined', COLORS.penile_bulb) # JSK 16.02.2023
x_rectum = ROI.ROI('xRectum', 'Undefined', COLORS.rectum)
x_anal_canal = ROI.ROI('xAnalCanal', 'Undefined', COLORS.anal_canal)
z_eye_l = ROI.ROIWall('xEye_L','Undefined', COLORS.wall, eye_l, 0, 0.2)
z_eye_r = ROI.ROIWall('xEye_R','Undefined', COLORS.wall, eye_r, 0, 0.2)
x_sparevolum = ROI.ROI('xSparevolum','Undefined', COLORS.x_sparevolum)
x_skulder_h = ROI.ROI('xSkulder_H','Undefined',COLORS.x_sparevolum)
x_skulder_v = ROI.ROI('xSkulder_V','Undefined',COLORS.x_sparevolum)
x_bekkenbein = ROI.ROI('xBekkenbein','Undefined',COLORS.x_bekkenbein)
x_body_ptv_n = ROI.ROI('xBody-PTVn','Undefined',COLORS.z_mask) 
x_bowelbag_ptv_n = ROI.ROI('xBowelBag-PTVn','Undefined',COLORS.x_bowelbag_ptv_n) 
x_rectum_ptv_n = ROI.ROI('xRectum-PTVn','Undefined',COLORS.x_rectum_ptv_n) 
x_bladder_ptv_n = ROI.ROI('xBladder-PTVn','Undefined',COLORS.x_bladder_ptv_n) 
x_sigmoid_ptv_n = ROI.ROI('xSigmoid-PTVn','Undefined',COLORS.x_sigmoid_ptv_n) 
x_chestwall = ROI.ROI('xChestwall','Undefined',COLORS.chestwall)
y_chestwall = ROI.ROI('yChestwall','Undefined',COLORS.chestwall)
x_trachea_bronchus = ROI.ROI('xTrachea_Bronchus','Undefined', COLORS.trachea)
x_a_aorta = ROI.ROI('xA_Aorta','Undefined', COLORS.aorta)
cv_lungs = ROI.ROI('CV_Lungs','Undefined', COLORS.cv)
cv_liver = ROI.ROI('CV_Liver','Undefined', COLORS.cv)
cv_kidneys = ROI.ROI('CV_Kidneys','Undefined', COLORS.cv)
cv_kidney_l = ROI.ROI('CV_Kidney_L','Undefined', COLORS.cv)
cv_kidney_r = ROI.ROI('CV_Kidney_R','Undefined', COLORS.cv)
bone = ROI.ROI('Bone','Undefined', COLORS.cv)
dorso_rectum = ROI.ROI('zRectum_P', 'Undefined', COLORS.dorso_rectum)
z_rectum_p = ROI.ROI('zRectum_P', 'Undefined', COLORS.dorso_rectum)
x_body_fripust = ROI.ROI('xBody_fripust', 'Control', COLORS.x_body_fripust)
sternum_box = ROI.ROI('xSternumBox','Undefined', COLORS.mask_ptv)

# Walls/Rings
x_ptv_ring_05 =  ROI.ROI('xPTV_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv1_ring_05 =  ROI.ROI('xPTV1_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv2_ring_05 =  ROI.ROI('xPTV2_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv3_ring_05 =  ROI.ROI('xPTV3_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv4_ring_05 =  ROI.ROI('xPTV4_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv_ring_1 =  ROI.ROI('xPTV_Ring0-1cm', 'Undefined', COLORS.wall)
x_ptv1_ring_1 =  ROI.ROI('xPTV1_Ring0-1cm', 'Undefined', COLORS.wall)
x_ptv2_ring_1 =  ROI.ROI('xPTV2_Ring0-1cm', 'Undefined', COLORS.wall)
x_ptv3_ring_1 =  ROI.ROI('xPTV3_Ring0-1cm', 'Undefined', COLORS.wall)
x_ptv4_ring_1 =  ROI.ROI('xPTV4_Ring0-1cm', 'Undefined', COLORS.wall)
x_ptv_ring_2 =  ROI.ROI('xPTV_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ptv1_ring_2 =  ROI.ROI('xPTV1_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ptv2_ring_2 =  ROI.ROI('xPTV2_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ptv3_ring_2 =  ROI.ROI('xPTV3_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ptv4_ring_2 =  ROI.ROI('xPTV4_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ptv_ring_15 = ROI.ROI('xPTV_Ring0-1.5cm', 'Undefined', COLORS.wall)
x_ctv_n_ring = ROI.ROI('xCTVn_L3-L4_Ring', 'Undefined', COLORS.wall)

# Matching structures
z_match = ROI.ROI('zMatch', 'Registration', COLORS.match)
z_match_r = ROI.ROI('zMatch_R', 'Registration', COLORS.match)
z_match_l = ROI.ROI('zMatch_L', 'Registration', COLORS.match)
z_match_sternum = ROI.ROI('zMatch_Sternum', 'Registration', COLORS.match)
z_mask = ROI.ROI('zMask','Undefined',COLORS.z_mask)
z_crp = ROI.ROI('zCRP', 'Undefined', COLORS.wall)
z_psv_green = ROI.ROI('zPSV_grønn','Undefined',COLORS.z_psv_green)
z_psv_yellow = ROI.ROI('zPSV_gul','Undefined',COLORS.z_psv_yellow)
z_psv_purple = ROI.ROI('zPSV_lilla','Undefined',COLORS.z_psv_purple)
z_psv_red = ROI.ROI('zPSV_rød','Undefined',COLORS.z_psv_red)
z_kontroll = ROI.ROI('zKontroll','Undefined',COLORS.z_toleranse)
z_toleranse_spinal_canal = ROI.ROI('zToleranse_SpinalCanal','Undefined',COLORS.z_toleranse)

# Optimization volumes
x_tetthetsvolum = ROI.ROI('xTetthetsvolum', 'Undefined', COLORS.wall)
x_tetthetsvolum_r = ROI.ROI('xTetthetsvolum_R', 'Undefined', COLORS.wall)
x_tetthetsvolum_l = ROI.ROI('xTetthetsvolum_L', 'Undefined', COLORS.wall)
x_tetthetsvolum_sternum = ROI.ROI('xTetthetsvolum_Sternum', 'Undefined', COLORS.wall)
z_water =  ROI.ROI('zWater', 'Undefined', COLORS.other_ptv)

# Other temp volumes:
z_temp_grey_level = ROI.ROI('zTempGreyLevel','Undefined',COLORS.z_mask)
z_temp_grey_level_and_oars = ROI.ROI('zTempGreyLevel_AND_OARs','Undefined',COLORS.z_mask)
z_temp_grey_level_and_oars_and_box = ROI.ROI('zTempGreyLevel_AND_OARs_AND_Box','Undefined',COLORS.z_mask)
temp_target_lung =  ROI.ROI('tempTargetLung','Undefined',COLORS.z_mask)
temp_chestwall =  ROI.ROI('TempChestwall','Undefined',COLORS.z_mask)
box = ROI.ROI('zBox','Undefined', COLORS.mask_ptv)
box1 = ROI.ROI('zBox1','Undefined', COLORS.mask_ptv)
box2 = ROI.ROI('zBox2','Undefined', COLORS.mask_ptv)
box_l = ROI.ROI('xBox_L','Undefined', COLORS.mask_ptv)
box_r = ROI.ROI('xBox_R','Undefined', COLORS.mask_ptv)
box3 = ROI.ROI('zBox3','Undefined', COLORS.mask_ptv)
box4 = ROI.ROI('zBox4','Undefined', COLORS.mask_ptv)
box5 = ROI.ROI('zBox5','Undefined', COLORS.mask_ptv)
x_l2_l4 = ROI.ROI('xL2-L4','Undefined', COLORS.mask_ptv)
fix_box = ROI.ROI('fixBox','Undefined', COLORS.wall)

# ROIS for optimization, isodose volumes
iso40 = ROI.ROI('40', 'Undefined', COLORS.x_sparevolum)
iso46 = ROI.ROI('46', 'Undefined', COLORS.x_sparevolum)
iso47_3 = ROI.ROI('47.3', 'Undefined', COLORS.z_mask)
iso50 = ROI.ROI('50', 'Undefined', COLORS.x_sparevolum)
iso52 = ROI.ROI('52', 'Undefined', COLORS.x_sparevolum)
iso52_5 = ROI.ROI('52.5', 'Undefined', COLORS.x_sparevolum)
iso55 = ROI.ROI('55', 'Undefined', COLORS.x_sparevolum)
iso56_7 = ROI.ROI('56.7', 'Undefined', COLORS.x_sparevolum)
iso58_5 = ROI.ROI('58.5', 'Undefined', COLORS.z_mask)
iso60 = ROI.ROI('60', 'Undefined', COLORS.cv)
iso63 = ROI.ROI('63', 'Undefined', COLORS.z_mask)
iso70 = ROI.ROI('70', 'Undefined', COLORS.cv)
iso73 = ROI.ROI('73', 'Undefined', COLORS.z_mask)
x40 = ROI.ROI('x40', 'Undefined', COLORS.x_sparevolum)
x46 = ROI.ROI('x46', 'Undefined', COLORS.x_sparevolum)
x47_3 = ROI.ROI('x47.3', 'Undefined', COLORS.cv)
x50 = ROI.ROI('x50', 'Undefined', COLORS.x_sparevolum)
x52 = ROI.ROI('x52', 'Undefined', COLORS.x_sparevolum)
x52_5 = ROI.ROI('x52.5', 'Undefined', COLORS.z_mask)
x55 = ROI.ROI('x55', 'Undefined', COLORS.x_sparevolum)
x56_7 = ROI.ROI('x56.7', 'Undefined', COLORS.z_mask)
x58_5 = ROI.ROI('x58.5', 'Undefined', COLORS.z_mask)
x60 = ROI.ROI('x60', 'Undefined', COLORS.cv)
x63 = ROI.ROI('x63', 'Undefined', COLORS.z_mask)
x67_5 = ROI.ROI('x67.5', 'Undefined', COLORS.cv)
x70 = ROI.ROI('x70', 'Undefined', COLORS.cv)
x77 = ROI.ROI('x77', 'Undefined', COLORS.cv)
x40_ptv = ROI.ROI('x40-PTV', 'Undefined', COLORS.wall)
x46_ptv = ROI.ROI('x46-PTV', 'Undefined', COLORS.x_sparevolum)
x52_ptv = ROI.ROI('x52-PTV', 'Undefined', COLORS.x_sparevolum)
x55_ptv = ROI.ROI('x55-PTV', 'Undefined', COLORS.x_sparevolum)
x_OAR_47_3 = ROI.ROI('xOAR47.3','Undefined', COLORS.ovary)
idl_12_5 = ROI.ROI('IDL_12.5','Undefined', COLORS.mask_ptv)
idl_10_5 = ROI.ROI('IDL_10.5','Undefined', COLORS.mask_ptv)
iso104= ROI.ROI('104', 'Undefined', COLORS.wall)

