#github-action genshdoc
- name: Generate Documentation
  # You may pin to the exact commit or the version.
  # uses: vargiuscuola/genshdoc@0f2a1895670c474de679631a33eae9369743af5f
  uses: vargiuscuola/genshdoc@v1.0
